spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filrouge?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      properties:
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
    show-sql: true
